### ISSUE TITLE
Server UPS drops when many trains waiting

### ISSUE THREAD

**Issue by legonigel** [Godmave/clusterioTrainTeleports#6]
Experienced on clustorio gridlock Ceres. There were a lot of trains waiting and the server would do a few updates, then slow way down, then do few updates. 

I think there is some problem with the retry logic not waiting between tries.

**Comment by Godmave** [comment]
It is waiting 2 seconds to retry. Just don't have too many trains, problem solved. That's part of the logistic problem...

**Comment by legonigel** [comment]
I think the retry logic doesn't actually work correctly in some cases.

**Comment by legonigel** [comment]
https://github.com/Godmave/clusterioTrainTeleports/blob/01a3933dbc6be6b1840ebdce4ac6e434e94508f9/lua/train_tracking.lua#L699
If this IF is true, then v.lastTry is set to nil, which causes the if to pass the next time. Maybe the NOT needs to be removed?

**Comment by legonigel** [comment]
See #7

**Comment by Godmave** [comment]
if v.lastTry is nil, it will go in since it has not tried yet
if v.lastTry is not nil it will go to the next condition v.lastTry > event.tick - TELEPORT_COOLDOWN_TICKS, which would be true, if the v.lastTry was less than TELEPORT_COOLDOWN_TICKS ago and thus would not do anything this time around either.

If v.lastTry is nil, you don't want it to wait the 2 seconds, or it will take 2 seconds for each reroute to the next stop too.

**Comment by legonigel** [comment]
It appears that `v.lastTry` is not set if a station is found and all stations are blocked. A valid station is returned from `find_station` as long as one exists on the map even if it is blocked, so L793 should always be true. Maybe I misunderstand the code, but it seems like it will never sleep in this case.
 https://github.com/Godmave/clusterioTrainTeleports/blob/15845c411295af32bfd6dd3cd4dc5313818a070d/lua/train_tracking.lua#L793
